services:
  postgres:
    image: postgres:16
    container_name: learning_platform_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: webtech
      POSTGRES_USER: webtech
      POSTGRES_PASSWORD: webtech_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mongodb:
    image: mongo:7
    container_name: learning_platform_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
